# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Cloudtips-SDK-iOS-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Cloudtips-SDK-iOS', :path => "../sdk"
  pod 'Cloudpayments-SDK-iOS', :git => "https://github.com/cloudpayments/CloudPayments-SDK-iOS-V2"

end
