# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

target 'Cloudtips-SDK-iOS' do
  pod 'Alamofire', '5.0.0-rc.2'
  pod 'AlamofireObjectMapper'
  pod 'SDWebImage', '~> 5.0'
  pod 'Cloudpayments', :git => "https://github.com/cloudpayments/CloudPayments-SDK-iOS-V2", :branch => "master"

end
